apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-devops-app
  template:
    metadata:
      labels:
        app: simple-devops-app
    spec:
      containers:
      - name: simple-devops-app
        image: amirhamjahd/simple-devops-app:latest
        ports:
        - containerPort: 5000

