apiVersion: v1
kind: Service
metadata:
  name: simple-devops-service
spec:
  selector:
    app: simple-devops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

